name: Generate Snake

on:
  schedule:
    # Dijalankan otomatis setiap 24 jam sekali
    - cron: "0 0 * * *"
  
  # Memungkinkan Anda menjalankan workflow secara manual dari tab Actions di GitHub
  workflow_dispatch:
  
  # Dijalankan saat ada pembaruan pada branch utama
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Menghasilkan animasi game ular berdasarkan kontribusi GitHub pengguna
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Unggah hasil output ke branch 'output' agar dapat diakses secara publik
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
